services:
  kodi:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        KODI_VERSION: 21.1-Omega
    image: yrzr/kodi-gbm:rk35xx
    container_name: kodi-gbm
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 2G
    privileged: true
    restart: unless-stopped
    environment:
      - WEBSERVER_ENABLED=true
      - WEBSERVER_PORT=8080
      - WEBSERVER_AUTHENTICATION=true
      - WEBSERVER_USERNAME=kodi
      - WEBSERVER_PASSWORD=kodi
    ports:
      # web interface
      - 8080:8080
      # json-rpc
      - 9090:9090
      # EventServer
      - 9777:9777/udp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /media:/media:ro
      - ./data:/usr/local/share/kodi/portable_data
    # entrypoint: /usr/local/bin/kodi-standalone
    # command: --logging=console --portable --debug
