services:
  kodi:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        KODI_VERSION: 21.2-Omega
    image: yrzr/kodi-gbm:rk35xx
    container_name: kodi-gbm
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
    privileged: true
    restart: unless-stopped
    environment:
      - TZ=Asia/Hong_Kong
      - WEBSERVER_ENABLED=true
      - WEBSERVER_PORT=8080
      - WEBSERVER_AUTHENTICATION=true
      - WEBSERVER_USERNAME=kodi
      - WEBSERVER_PASSWORD=kodi
    network_mode: "host"
    volumes:
      - ./data:/usr/share/kodi/portable_data
      - /media:/media:ro
    # command: --logging=console --portable --debug
